<?php

namespace Sari\UserBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Compte le nombre de résultat dans la table
     * @return mixed
     */
    public function count()
    {
        return $this->createQueryBuilder('u')->select('COUNT(u)')->getQuery()->getSingleScalarResult();
    }

    /**
     * Affiche les joueurs avec le champ deletedAt
     * @return array
     */
    public function findDeleted()
    {
        return $this->createQueryBuilder('u')->select('u')->where('u.deletedAt IS NOT NULL')->orderBy('u.deletedAt', 'DESC')->getQuery();
    }

    public function search($search)
    {
        return $this->createQueryBuilder('u')->select('u')->where('LOWER(u.username) LIKE :search OR LOWER(u.email) LIKE :search')
            ->setParameter('search', '%' . $search . '%')->getQuery();
    }
}
