# FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Sari\UserBundle\Entity\Utilisateur
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        no_reply@iutdelens.fr
        sender_name:    IUT de Lens - Ne pas répondre à ce mail
    registration:
        form:
            type: Sari\UserBundle\Form\RegistrationFormType
        confirmation:
            enabled: true
            template: SariUserBundle:Registration:email.html.twig
    resetting:
        email:
            template: SariUserBundle:Resetting:email.html.twig
    profile:
        form:
            type: Sari\UserBundle\Form\ProfileFormType
